refactor: update to current auro components
AlaskaAirlines/AuroReactDemo pull request #17
Opened 2021-05-13 19:39 UTC by jason-capsule42

# Alaska Airlines Pull Request

**Fixes:** # (issue, if applicable)

## Summary:

Updates the demo project to match current Auro components, removes old Orion components, updates Husky and switches node-sass out for dart-sass.

## Type of change:

Please delete options that are not relevant.

- [ ] New capability 
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate) 

## Checklist:

- [ ] My update follows the CONTRIBUTING guidelines of this project
- [ ] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._ 

**Thank you for your submission!**<br>
-- Orion Design System Team

2021-05-13 20:32 UTC, blackfalcon requested changes
I feel a compelling demo would be to build a form using the various form elements. allowing a user to enter their data and have an interesting way to return that data. 

Incorporate other things like icons, dialog windows, auro-header, etc... 

What can we do with this demo to illustrate a rich interface using Auro?

2021-05-13 20:32 UTC, blackfalcon commented on README.md
> +![Travis (.org)](https://img.shields.io/travis/alaskaairlines/auroreactdemo?style=for-the-badge) ![GitHub tag (latest by date)](https://img.shields.io/github/v/tag/AlaskaAirlines/AuroReactDemo?style=
This should be removed. We aren't using Travis for anything anymore. Or at least, we shouldn't.

2021-05-13 20:32 UTC, blackfalcon commented on README.md
> +This resource is built using Sass, [node-sass](https://www.npmjs.com/package/node-sass) is the preferred library for Create React App.
Do we want to update this to use dart-sass now that node-sass is dead?

2021-05-19 18:41 UTC, jason-capsule42 commented
I've updated this PR with significant changes to the content of the demo itself. It is now a form with two required inputs, a required radio button and a dynamic optional checkbox group that shows up only if the appropriate option is selected in the radio group. The submit button is disabled until all required fields are completed.

2021-05-21 18:14 UTC, blackfalcon requested changes

2021-05-21 18:14 UTC, blackfalcon commented on README.md
> +The following command will install [auro-button](http://auro.alaskaair.com/components/auro/button), [design tokens](http://auro.alaskaair.com/getting-started/developers/design-tokens) and focus-visib
This should be updated to include the other auro custom elements being installed.

2021-05-21 18:14 UTC, blackfalcon commented on README.md
> +### Web components manifest
@geoffrich what do you say about removing all of this? Very soon we will be dropping IE support and this is no longer needed.

2021-05-21 18:14 UTC, blackfalcon commented on README.md
> +This resource is built using Sass, [node-sass](https://www.npmjs.com/package/node-sass) is the preferred library for Create React App.
Yes, I see that in the package.json you are using `"sass": "^1.32.13"`, so this needs to be updated as well.

2021-05-21 18:14 UTC, blackfalcon commented on README.md
> +After installing `sass`, rename `index.css` to `index.scss` and rename the import in `index.js`.
:+1:

2021-05-21 18:14 UTC, blackfalcon commented on README.md
> +## IE11 support
@geoffrich more on dropping IE. What say we all?

2021-05-21 18:14 UTC, blackfalcon commented on README.md
> +### Delete the .cache
Samzies.

2021-05-21 18:14 UTC, blackfalcon commented on package.json
>    "version": "1.1.0",
This commit should be updated with a BREAKING CHANGE message to release a v2.0 

https://github.com/AlaskaAirlines/WC-Generator/blob/master/template/.github/CONTRIBUTING.md#major

2021-05-21 21:53 UTC, geoffrich commented on README.md
> +### Web components manifest
I think it makes sense to remove it. If we don't need to support IE, I believe we can remove a lot of the demo setup
- no need for webcomponents-loader
- no need for a manifest, Auro components can be imported directly into the React components that need them
- polyfill imports can be removed and IE11 doesn't need to be added to browserslist

2021-05-23 18:24 UTC, blackfalcon commented on README.md
> +### Web components manifest
Agreed. The next major version of the demos can chill-lax on the IE support. 

I'd add something in the README @jason-capsule42 that links to the legacy code if someone wants to dig into that.

2021-05-25 17:52 UTC, blackfalcon requested changes
One minor content update and it looks great!

2021-05-25 17:52 UTC, blackfalcon commented on README.md
> +* focus-visible
oops... I feel like there is something missing here?

2021-05-26 23:54 UTC, jason-capsule42 commented on README.md
> +* focus-visible
What is missing, @blackfalcon?

2021-05-27 14:55 UTC, geoffrich commented on README.md
> +* focus-visible
Maybe a link to [focus-visible](https://github.com/WICG/focus-visible)?

Also, looks like the auro-input link goes to header instead of input.

2021-05-27 15:00 UTC, jason-capsule42 commented on README.md
> +* focus-visible
Thanks, Geoff. Updated added.

2021-05-27 18:47 UTC, blackfalcon approved these changes

2021-05-27 18:48 UTC, merged

2021-05-27 18:49 UTC, ecommerceUXdesign commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on [GitHub release](https://github.com/AlaskaAirlines/AuroReactDemo/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: